### ISSUE TITLE
Weekly total still not resetting..

### ISSUE THREAD

**Issue by foladar** [DJDajn/Accountant#14]
Saw there was at least 3 others that had this issue, even though I am on the newest version, it's still not reset for this week as of 3am.

**Comment by DJDajn** [comment]
This was fixed in the 8.0.1.17, so please make sure this is the version that you're using. 
Also, you have to force the update by either clicking the minimap button to bring up the ui, reload or relog.
It wont auto update as it wouldn't work anymore.

With regards, 
Dajn

**Comment by foladar** [comment]
I am definitely on .17, I've relogged and reloaded the UI, it is still not updating. Still has my totals from last week.

**Comment by DJDajn** [comment]
Will look into it then, worked fine when I was testing it everything before I released it

**Comment by DJDajn** [comment]
Just checked and everything works for me, so please change the reset day to another day and then change it back. Also, what operating system are you using? OS X, Windows, Unix?

**Comment by foladar** [comment]
Windows 10

**Comment by DJDajn** [comment]
Just to see if something is broken or not, can you change the reset day to tomorrow (if it's still the 28th for you) and open up the ui after midnight to check if the week tab was reset. If it's already the 29th, can you still try it? Just want to confirm if something is broken or not

**Comment by foladar** [comment]
I changed the reset day to Wednesday as it's still Tuesday, but it reset the counter. I assume it would reset again if it works properly?

**Comment by DJDajn** [comment]
yea, it will reset again if it's working like it should. So buy/sell something small just to get some data to test with and please let me know what the outcome is. :) 
Also, if you could post a screenshot of before and after the reset and a screenshot if you get any errors that would be great!

**Comment by foladar** [comment]
It showed +833k since I traded myself 1 mil gold, with reset day set to Wed. It's 12:41am, unless it goes by server time, and still shows the same amount. I'll double check when server time hits 12:00am
![wowscrnshot_082918_004226](https://user-images.githubusercontent.com/3710582/44765830-97473a00-ab24-11e8-8f9b-125501d34dff.jpg)
![wowscrnshot_082818_231436](https://user-images.githubusercontent.com/3710582/44765831-97473a00-ab24-11e8-96a6-87000a5ca203.jpg)

only Lua warnings I have is for deferred XML node object lib_UIdropdownmenubuttontemplate
 but I don't think that's related to Accountant

edit: i uploaded the images backwards, the after midnight is first, whoops

**Comment by foladar** [comment]
I've logged off for the night, come back on this morning and it's still showing the same totals (from yesterday).

**Comment by DJDajn** [comment]
Got some help from a few friends and all of their weeks did reset on the set date. So I would suggest a clean install of the addon if you haven't already tried that (reseting the config as well).

If that doesn't work, then I have no idea, as it works for multiple people I've asked to test it for me.

**Comment by BeLZeDaR666** [comment]
hmm 8.0.17 still isnt resetting for me on my chosen reset day (wednesday) i have followed the advice given to those above and still get the same issue having to reset the data myself. i will try a complete uninstall of the addon then re-install

** update **
have done a complete uninstall using the twitch app (clearing the addon setttingas well) and re-installed I will let you know if it resets
changed the day to Tuesday then back to Wednesday and it reset the total
 
12/09/18 Update: it didn't reset today on my chosen day had to reset it manually

**Comment by foladar** [comment]
Yeah, I uninstalled and reinstalled and it still isn't working for me either. I just have to reset it manually if I remember.

**Comment by Urdui** [comment]
I did a clean install. Deleted saved variables and THEN reinstalled. It seems to okay now.

**Comment by RudolphRiedel** [comment]
I just ended up here as I have the same issue.
So I just removed Account 8.0.1.17 and looked for its saved vars but could not find any.
It should be in the wtf drawer, but under what name?

I re-installed it and used the "Clear Data" button from the Accountant preferences, I hope that fixes it.

**Comment by RudolphRiedel** [comment]
Looks like the data-broker interface is a bit broken: 
![account_databroker_display](https://user-images.githubusercontent.com/31180093/45257186-5bbd3300-b3a2-11e8-8e08-6bdac268cfc0.png)

Although I selected "Week" it displays the amout that I made in the session and writes whatever is selected next to that amount.
And "session" is the default for the minimap-button.
When I change the setup for the minimap-button to "Week" that amount is displayed in the TitanPanel bar along with "Sess", "Day", "Week" or "Tot" next to it.

So in order to see the amount for the week I need to not only select the "Week" tab as before, but also change the setup for the minimap-button accordingly.
And it does not matter if the minimap-button is displayed or not.

**Comment by BeLZeDaR666** [comment]
> I did a clean install. Deleted saved variables and THEN reinstalled. It seems to okay now.

where did you find these ?

**Comment by BeLZeDaR666** [comment]
> I just ended up here as I have the same issue.
> So I just removed Account 8.0.1.17 and looked for its saved vars but could not find any.
> It should be in the wtf drawer, but under what name?
> 
> I re-installed it and used the "Clear Data" button from the Accountant preferences, I hope that fixes it.

hasn't fixed it for me

**Comment by Urdui** [comment]
I install most of my add on thru Twitch's interface so I used Twitch's "Delete Settings (Saved Variables)" option. Then used their Delete feature. Then I went back in and had Twitch reinstall the add on. Everything works okay now. If you want to delete them manually you go into the World of Warcraft/WTF/Account/[account name]/SavedVariables/ folder and delete the .lua and .bak files for Accountant, for each account you have. Or if you're not worried about losing any variables for any other add on just delete the whole WTF folder (WoW will make a new one).

**Comment by foladar** [comment]
still no fix?

**Comment by BeLZeDaR666** [comment]
> still no fix?

nope

**Comment by Urdui** [comment]
I guess I spoke too soon. I had it reset once after I deleted my saved variables and did a completely fresh reinstall,  so I thought it was working, but it didn't reset this week. I have Tuesday set as my reset day.

**Comment by BeLZeDaR666** [comment]
> Looks like the data-broker interface is a bit broken:
> ![account_databroker_display](https://user-images.githubusercontent.com/31180093/45257186-5bbd3300-b3a2-11e8-8e08-6bdac268cfc0.png)
> 
> Although I selected "Week" it displays the amout that I made in the session and writes whatever is selected next to that amount.
> And "session" is the default for the minimap-button.
> When I change the setup for the minimap-button to "Week" that amount is displayed in the TitanPanel bar along with "Sess", "Day", "Week" or "Tot" next to it.
> 
> So in order to see the amount for the week I need to not only select the "Week" tab as before, but also change the setup for the minimap-button accordingly.
> And it does not matter if the minimap-button is displayed or not.

This seems to have worked for me now, i had it reseting friday but i changed it to wednesday and reset so hopefully this has cured the problem. i will find out this wednesday coming :D 

RESET IS NOW WORKING FOR ME AFTER FOLLOWING THIS ADVICE

**Comment by frolick** [comment]
I noticed that none of the date fields in the savedvariables file include the day of the month because all of the string.sub(cdate,0,8) calls cut off the day. If you change the 8 to a 10 in all of the string.sub(cdate,0,8) calls in the Accountant.lua file and change the day of the week Acountant refreshes, the addon will write out the day of the month in the savedvariables file. It will also display the date in the "Week Start" field as seen in BelzeDaR666's image above. 

I don't know if that fixes the issue, but it might help track it down.

**Comment by foladar** [comment]
so is this abandoned then? so i know to look for another alternative..

**Comment by frolick** [comment]
> 
> 
> so is this abandoned then? so i know to look for another alternative..

It looks that way. 

The fix that seemed to work for me is to change the 3 instances of: 

`string.sub(wdate,0,8)` to `string.sub(wdate,0,10)`

These are found on lines 1158, 1321, and 1959 of the Accountant.lua file in the addon directory. 

You also have to add a line to the file. On a new line after line 1174 (`dateformat=2,`) add: `weekreset=nil,`

With WoW closed, go into the SavedVariables folder of your WoW install (World of Warcraft\WTF\Account\ACCOUNTNAME\SavedVariables) and delete Accountant.lua and Accountant.lua.bak. 

Once you have WoW started back up, you can set the day of the week you want the reset for and then cycle through all your characters.
